COUNTRIES = [
  [ "United States", 'US'],
  [ "---", '--'],
  [ "Afghanistan", "AF" ],
  [ "Albania", "AL" ],
  [ "Algeria", "DZ" ],
  [ "Andorra", "AD" ],
  [ "Angola", "AO" ],
  [ "Anguilla", "AI" ],
  [ "Antigua and Barbuda", "AG" ],
  [ "Argentina", "AR" ],
  [ "Armenia", "AM" ],
  [ "Aruba", "AW" ],
  [ "Australia", "AU" ],
  [ "Austria", "AT" ],
  [ "Azerbaijan", "AZ" ],
  [ "Bahamas", "BS" ],
  [ "Bahrain", "BH" ],
  [ "Bangladesh", "BD" ],
  [ "Barbados", "BB" ],
  [ "Belarus", "BY" ],
  [ "Belgium", "BE" ],
  [ "Belize", "BZ" ],
  [ "Benin", "BJ" ],
  [ "Bermuda", "BM" ],
  [ "Bhutan", "BT" ],
  [ "Bolivia", "BO" ],
  [ "Bosnia and Herzegovina", "BA" ],
  [ "Botswana", "BW" ],
  [ "Brazil", "BR" ],
  [ "British Virgin Islands", "VG" ],
  [ "Brunei Darussalam", "BN" ],
  [ "Bulgaria", "BG" ],
  [ "Burkina Faso", "BF" ],
  [ "Burma (Myanmar)", "MM" ],
  [ "Burundi", "BI" ],
  [ "Cambodia (Kampuchea)", "KH" ],
  [ "Cameroon", "CM" ],
  [ "Canada", "CA" ],
  [ "Cape Verde", "CV" ],
  [ "Cayman Islands", "KY" ],
  [ "Central African Republic", "CF" ],
  [ "Chad", "TD" ],
  [ "Chile", "CL" ],
  [ "China", "CN" ],
  [ "Colombia", "CO" ],
  [ "Comoros", "KM" ],
  [ "Congo, Democratic Republic of the", "CD" ],
  [ "Congo, Republic of the (Brazzaville)", "CG" ],
  [ "Costa Rica", "CR" ],
  [ "Cote d'Ivoire (Ivory Coast)", "CI" ],
  [ "Croatia", "HR" ],
  [ "Cuba", "CU" ],
  [ "Cyprus", "CY" ],
  [ "Czech Republic", "CZ" ],
  [ "Denmark", "DK" ],
  [ "Djibouti", "DJ" ],
  [ "Dominica", "DM" ],
  [ "Dominican Republic", "DO" ],
  [ "Ecuador", "EC" ],
  [ "Egypt", "EG" ],
  [ "El Salvador", "SV" ],
  [ "Equatorial Guinea", "GQ" ],
  [ "Eritrea", "ER" ],
  [ "Estonia", "EE" ],
  [ "Ethiopia", "ET" ],
  [ "Falkland Islands", "FK" ],
  [ "Faroe Islands", "FO" ],
  [ "Fiji", "FJ" ],
  [ "Finland", "FI" ],
  [ "France", "FR" ],
  [ "French Guiana", "GF" ],
  [ "French Polynesia", "PF" ],
  [ "Gabon", "GA" ],
  [ "Gambia", "GM" ],
  [ "Georgia, Republic of", "GE" ],
  [ "Germany", "DE" ],
  [ "Ghana", "GH" ],
  [ "Gibraltar", "GI" ],
  [ "Great Britain and Northern Ireland", "GB" ],
  [ "Greece", "GR" ],
  [ "Greenland", "GL" ],
  [ "Grenada", "GD" ],
  [ "Guadeloupe", "GP" ],
  [ "Guatemala", "GT" ],
  [ "Guinea", "GN" ],
  [ "Guinea-Bissau", "GW" ],
  [ "Guyana", "GY" ],
  [ "Haiti", "HT" ],
  [ "Honduras", "HN" ],
  [ "Hong Kong", "HK" ],
  [ "Hungary", "HU" ],
  [ "Iceland", "IS" ],
  [ "India", "IN" ],
  [ "Indonesia", "ID" ],
  [ "Iran", "IR" ],
  [ "Iraq", "IQ" ],
  [ "Ireland", "IE" ],
  [ "Israel", "IL" ],
  [ "Italy", "IT" ],
  [ "Jamaica", "JM" ],
  [ "Japan", "JP" ],
  [ "Jordan", "JO" ],
  [ "Kazakhstan", "KZ" ],
  [ "Kenya", "KE" ],
  [ "Kiribati", "KI" ],
  [ "Korea, Democratic People's Republic of (North Korea)", "KP" ],
  [ "Korea, Republic of (South Korea)", "KR" ],
  [ "Kuwait", "KW" ],
  [ "Kyrgyzstan", "KG" ],
  [ "Laos", "LA" ],
  [ "Latvia", "LV" ],
  [ "Lebanon", "LB" ],
  [ "Lesotho", "LS" ],
  [ "Liberia", "LR" ],
  [ "Libya", "LY" ],
  [ "Liechtenstein", "LI" ],
  [ "Lithuania", "LT" ],
  [ "Luxembourg", "LU" ],
  [ "Macao", "MO" ],
  [ "Macedonia (Republic of)", "MK" ],
  [ "Madagascar", "MG" ],
  [ "Malawi", "MW" ],
  [ "Malaysia", "MY" ],
  [ "Maldives", "MV" ],
  [ "Mali", "ML" ],
  [ "Malta", "MT" ],
  [ "Martinique", "MQ" ],
  [ "Mauritania", "MR" ],
  [ "Mauritius", "MU" ],
  [ "Mexico", "MX" ],
  [ "Moldova", "MD" ],
  [ "Mongolia", "MN" ],
  [ "Montenegro, Republic of", "ME" ],
  [ "Montserrat", "MS" ],
  [ "Morocco", "MA" ],
  [ "Mozambique", "MZ" ],
  [ "Namibia", "NA" ],
  [ "Nauru", "NR" ],
  [ "Nepal", "NP" ],
  [ "Netherlands", "NL" ],
  [ "Netherlands Antilles", "AN" ],
  [ "New Caledonia", "NC" ],
  [ "New Zealand", "NZ" ],
  [ "Nicaragua", "NI" ],
  [ "Niger", "NE" ],
  [ "Nigeria", "NG" ],
  [ "Norway", "NO" ],
  [ "Oman", "OM" ],
  [ "Pakistan", "PK" ],
  [ "Panama", "PA" ],
  [ "Papua New Guinea", "PG" ],
  [ "Paraguay", "PY" ],
  [ "Peru", "PE" ],
  [ "Philippines", "PH" ],
  [ "Pitcairn Island", "PN" ],
  [ "Poland", "PL" ],
  [ "Portugal", "PT" ],
  [ "Qatar", "QA" ],
  [ "Reunion", "RE" ],
  [ "Romania", "RO" ],
  [ "Russia", "RU" ],
  [ "Rwanda", "RW" ],
  [ "Saint Christopher and Nevis", "KN" ],
  [ "Saint Helena", "SH" ],
  [ "Saint Lucia", "LC" ],
  [ "Saint Pierre and Miquelon", "PM" ],
  [ "Saint Vincent and the Grenadines", "VC" ],
  [ "San Marino", "SM" ],
  [ "Sao Tome and Principe", "ST" ],
  [ "Saudi Arabia", "SA" ],
  [ "Senegal", "SN" ],
  [ "Serbia, Republic of", "RS" ],
  [ "Seychelles", "SC" ],
  [ "Sierra Leone", "SL" ],
  [ "Singapore", "SG" ],
  [ "Slovak Republic (Slovakia)", "SK" ],
  [ "Slovenia", "SI" ],
  [ "Solomon Islands", "SB" ],
  [ "Somalia", "SO" ],
  [ "South Africa", "ZA" ],
  [ "Spain", "ES" ],
  [ "Sri Lanka", "LK" ],
  [ "Sudan", "SD" ],
  [ "Suriname", "SR" ],
  [ "Swaziland", "SZ" ],
  [ "Sweden", "SE" ],
  [ "Switzerland", "CH" ],
  [ "Syrian Arab Republic (Syria)", "SY" ],
  [ "Taiwan", "TW" ],
  [ "Tajikistan", "TJ" ],
  [ "Tanzania", "TZ" ],
  [ "Thailand", "TH" ],
  [ "Togo", "TG" ],
  [ "Tonga", "TO" ],
  [ "Trinidad and Tobago", "TT" ],
  [ "Tunisia", "TN" ],
  [ "Turkey", "TR" ],
  [ "Turkmenistan", "TM" ],
  [ "Turks and Caicos Islands", "TC" ],
  [ "Tuvalu", "TV" ],
  [ "Uganda", "UG" ],
  [ "Ukraine", "UA" ],
  [ "United Arab Emirates", "AE" ],
  [ "Uruguay", "UY" ],
  [ "Uzbekistan", "UZ" ],
  [ "Vanuatu", "VU" ],
  [ "Vatican City", "VA" ],
  [ "Venezuela", "VE" ],
  [ "Vietnam", "VN" ],
  [ "Wallis and Futuna Islands", "WF" ],
  [ "Western Samoa", "WS" ],
  [ "Yemen", "YE" ],
  [ "Zambia", "ZM" ],
  [ "Zimbabwe", "ZW" ]
]